version: 0.0
os: linux
files:
 - source: /src
   destination: /home/ubuntu/server
 - source: requirements.txt
   destination: /home/ubuntu/server
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: root