version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/server
hooks:
  AfterInstall:
   - location: scripts/install_dependencies.sh
     timeout: 60
     runas: root
   - location: scripts/start_server.sh
     timeout: 60
     runas: root
