version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/server
hooks:
  BeforeInstall:
   - location: scripts/install_dependencies
     timeout: 60
     runas: root
   - location: scripts/start_server
     timeout: 60
     runas: root