version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/server
 - source: requirements.txt
   destination: /home/ubuntu/server
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: ubuntu
   - location: scripts/start_server
     timeout: 300
     runas: ubuntu